# Extrassentials by Dartanman
Extrassentials-Join:
  Enabled: true
  Custom-Join-Message: '&7[&a+&7] &f<player>'
  Custom-Quit-Message: '&7[&c-&7] &f<player>'
  Silent-Join:
    Enabled: true
Extrassentials-Chat:
  Enabled: true
  Private-Message-Format:
    Sender: '&6You &f> &6<receiver>&f: <message>'
    Receiver: '&6<sender> &f> &6You&f: <message>'
Global-Messages:
  Must-Be-A-Player: '&cYou must be a player to do that!'
  Incorrect-Args: '&cIncorrect args! Try &e<suggestion>&c!'
  Target-Offline: '&cThat player is not online!'
  Insufficient-Permissions: '&cYou do not have permission for that!'